---
sudo: required
language: ruby
rvm:
  - 2.6.6
cache:
  node: true
  bundler: true
  yarn: true
  directories:
    - vendor/bundle
    - node_modules
    - public/assets
    - public/packs-test
    - $HOME/.nvm
services:
  - redis-server
before_install: gem install bundler -v 2.0.1
addons:
  postgresql: 10
  chrome: stable
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - yarn
  - bundle exec rails db:create RAILS_ENV=test
script:
  - bundle exec rake assets:precompile RAILS_ENV=test
  - bundle exec rails db:test:load RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
